# -*- coding: utf-8 -*-
"""Welcome_message.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O40SwAffTWMW-MXxNIUc443QHC-i3tlN

A short welcoming message for the Cloud Computing course
"""

print("Welcome to world of Cloud Computing")